name: AntiFelix
version: 1.0
description: AntiFelix for GMF-Network
author: GMF
authors: [GMF]
website: http://5.189.129.153/

main: com.gmf.antifelix.main.Main
database: false
depend:

commands:

permissions: