name: NoPhantoms
version: 1.0
description: Plugin that disables Phantoms.
author: GMF
authors: [GMF]
website: http://5.189.129.153/

main: com.gmf.nophantoms.main.Main
database: false
depend:

commands:

permissions: