name: GMF
version: 1.0
description:
author: Gamefors
authors: []
website: http://5.189.129.153:7000/

main: com.gamefors.gmf.main.Main
database: false
depend:

commands:
  gm:
    description: Set your gamemode.
    usage: /gm <gamemode>

permissions: