main: com.gmf.gmcrnetwork.main.Main

name: GMCR-Network

version: 1.0.0

api-version: 1.16

author: GMF

commands:

  lobby:
    aliases: [l,hub]

  addServer:
    aliases: [as]
    permission: gmcr.addserver

  removeServer:
    aliases: [rs]
    permission: gmcr.removeserver

  ping:
    aliases: [p]

  portBindings:
    aliases: [pb]
    permission: gmcr.portbindings